/**
 * ============================================================================
 * Token unlock calendar.
 * ============================================================================
 * The dataset is a build-time snapshot at `/data/unlocks.json`, generated by
 * scripts/generate-unlocks.mjs. See that file for where it comes from and what
 * is deliberately left out.
 *
 * The design decision that shapes every screen here: **rank by share of
 * circulating supply, not by dollar value.** A $40m unlock against a $6bn
 * float moves nothing; the same $40m against a $120m float is the only thing
 * that will matter to that token this month. Ranking by dollars sorts by market
 * cap with extra steps, which is why the dollar-sorted view of any unlock site
 * is the same handful of large caps every week.
 */

export type UnlockCategory =
  | "insiders"
  | "privateSale"
  | "publicSale"
  | "community"
  | "ecosystem"
  | "airdrop"
  | "farming"
  | "liquidity"
  | "staking"
  | "noncirculating"
  | "Uncategorized";

export interface UnlockRow {
  /** DefiLlama protocol slug. */
  slug: string;
  name: string;
  symbol: string | null;
  geckoId: string | null;
  /** ISO date of the release. */
  date: string;
  category: string;
  /** The real allocation names inside that bucket, e.g. ["Core Contributors"]. */
  groups: string[];
  /**
   * A cliff is one scheduled release; linear is a daily drip from a vesting
   * curve. They are shown differently because a cliff is an event and a drip
   * is a background condition — summing them into one number would hide every
   * cliff behind the emissions of whichever token vests fastest.
   */
  type: "cliff" | "linear";
  tokens: number;
  /** At the snapshot price. Null when the token has no price we could read. */
  usd: number | null;
  /** Null rather than 0 when unknown — an unknown share must not sort as safe. */
  pctOfCirculating: number | null;
  marketCap: number | null;
}

export interface UnlockData {
  asOf: string;
  horizonDays: number;
  source: string;
  rows: UnlockRow[];
}

/** Human labels for the raw category keys DefiLlama uses. */
export const CATEGORY_LABELS: Record<string, string> = {
  insiders: "Team & insiders",
  privateSale: "Private sale",
  publicSale: "Public sale",
  community: "Community",
  ecosystem: "Ecosystem",
  airdrop: "Airdrop",
  farming: "Farming rewards",
  liquidity: "Liquidity",
  staking: "Staking rewards",
  noncirculating: "Treasury & reserves",
  Uncategorized: "Unclassified",
};

/**
 * How much attention a release deserves, from its share of circulating supply.
 *
 * The thresholds are judgement, not arithmetic, and are set where they are
 * because below roughly 1% of float a release is inside normal daily volume
 * for almost any liquid token, and above 10% it is larger than most tokens
 * trade in a week.
 */
export function unlockSeverity(pct: number | null): "high" | "medium" | "low" | "unknown" {
  if (pct == null) return "unknown";
  if (pct >= 10) return "high";
  if (pct >= 1) return "medium";
  return "low";
}
