// GENERATED by scripts/generate-history.mjs — do not edit by hand.
// Re-run `npm run history` to refresh both this file and public/data/history/.

export interface HistoryMeta {
  slug: string;
  symbol: string;
  source: string;
  start: string;
  end: string;
  days: number;
}

export const historyIndex: HistoryMeta[] = [
  {
    "slug": "bitcoin",
    "symbol": "BTC",
    "source": "Bitstamp",
    "start": "2011-08-18",
    "end": "2026-08-10",
    "days": 5472
  },
  {
    "slug": "ethereum",
    "symbol": "ETH",
    "source": "Binance",
    "start": "2017-08-17",
    "end": "2026-08-10",
    "days": 3281
  },
  {
    "slug": "xrp",
    "symbol": "XRP",
    "source": "Binance",
    "start": "2018-05-04",
    "end": "2026-08-10",
    "days": 3021
  },
  {
    "slug": "bnb",
    "symbol": "BNB",
    "source": "Binance",
    "start": "2017-11-06",
    "end": "2026-08-10",
    "days": 3200
  },
  {
    "slug": "solana",
    "symbol": "SOL",
    "source": "Binance",
    "start": "2020-08-11",
    "end": "2026-08-10",
    "days": 2191
  },
  {
    "slug": "dogecoin",
    "symbol": "DOGE",
    "source": "Binance",
    "start": "2019-07-05",
    "end": "2026-08-10",
    "days": 2594
  },
  {
    "slug": "cardano",
    "symbol": "ADA",
    "source": "Binance",
    "start": "2018-04-17",
    "end": "2026-08-10",
    "days": 3038
  },
  {
    "slug": "tron",
    "symbol": "TRX",
    "source": "Binance",
    "start": "2018-06-11",
    "end": "2026-08-10",
    "days": 2983
  },
  {
    "slug": "avalanche",
    "symbol": "AVAX",
    "source": "Binance",
    "start": "2020-09-22",
    "end": "2026-08-10",
    "days": 2149
  },
  {
    "slug": "chainlink",
    "symbol": "LINK",
    "source": "Binance",
    "start": "2019-01-16",
    "end": "2026-08-10",
    "days": 2764
  },
  {
    "slug": "polkadot",
    "symbol": "DOT",
    "source": "Binance",
    "start": "2020-08-18",
    "end": "2026-08-10",
    "days": 2184
  },
  {
    "slug": "litecoin",
    "symbol": "LTC",
    "source": "Binance",
    "start": "2017-12-13",
    "end": "2026-08-10",
    "days": 3163
  },
  {
    "slug": "shiba-inu",
    "symbol": "SHIB",
    "source": "Binance",
    "start": "2021-05-10",
    "end": "2026-08-10",
    "days": 1919
  },
  {
    "slug": "sui",
    "symbol": "SUI",
    "source": "Binance",
    "start": "2023-05-03",
    "end": "2026-08-10",
    "days": 1196
  },
  {
    "slug": "algorand",
    "symbol": "ALGO",
    "source": "Binance",
    "start": "2019-06-22",
    "end": "2026-08-10",
    "days": 2607
  },
  {
    "slug": "tezos",
    "symbol": "XTZ",
    "source": "Binance",
    "start": "2019-09-24",
    "end": "2026-08-10",
    "days": 2513
  },
  {
    "slug": "stellar",
    "symbol": "XLM",
    "source": "Binance",
    "start": "2018-05-31",
    "end": "2026-08-10",
    "days": 2994
  },
  {
    "slug": "bitcoin-cash",
    "symbol": "BCH",
    "source": "Binance",
    "start": "2019-11-28",
    "end": "2026-08-10",
    "days": 2448
  },
  {
    "slug": "gram",
    "symbol": "GRAM",
    "source": "CoinGecko",
    "start": "2025-08-11",
    "end": "2026-08-10",
    "days": 365
  },
  {
    "slug": "hedera",
    "symbol": "HBAR",
    "source": "Binance",
    "start": "2019-09-29",
    "end": "2026-08-10",
    "days": 2508
  },
  {
    "slug": "polygon",
    "symbol": "POL",
    "source": "Binance",
    "start": "2024-09-13",
    "end": "2026-08-10",
    "days": 697
  },
  {
    "slug": "cosmos",
    "symbol": "ATOM",
    "source": "Binance",
    "start": "2019-04-29",
    "end": "2026-08-10",
    "days": 2661
  },
  {
    "slug": "hyperliquid",
    "symbol": "HYPE",
    "source": "CoinGecko",
    "start": "2025-08-11",
    "end": "2026-08-10",
    "days": 365
  },
  {
    "slug": "zcash",
    "symbol": "ZEC",
    "source": "Binance",
    "start": "2019-03-21",
    "end": "2026-08-10",
    "days": 2700
  },
  {
    "slug": "monero",
    "symbol": "XMR",
    "source": "CoinGecko",
    "start": "2025-08-11",
    "end": "2026-08-10",
    "days": 365
  },
  {
    "slug": "uniswap",
    "symbol": "UNI",
    "source": "Binance",
    "start": "2020-09-17",
    "end": "2026-08-10",
    "days": 2154
  },
  {
    "slug": "near",
    "symbol": "NEAR",
    "source": "Binance",
    "start": "2020-10-14",
    "end": "2026-08-10",
    "days": 2127
  },
  {
    "slug": "aave",
    "symbol": "AAVE",
    "source": "Binance",
    "start": "2020-10-15",
    "end": "2026-08-10",
    "days": 2126
  },
  {
    "slug": "cronos",
    "symbol": "CRO",
    "source": "CoinGecko",
    "start": "2025-08-11",
    "end": "2026-08-10",
    "days": 365
  },
  {
    "slug": "bittensor",
    "symbol": "TAO",
    "source": "Binance",
    "start": "2024-04-11",
    "end": "2026-08-10",
    "days": 852
  },
  {
    "slug": "internet-computer",
    "symbol": "ICP",
    "source": "Binance",
    "start": "2021-05-11",
    "end": "2026-08-10",
    "days": 1918
  },
  {
    "slug": "ethereum-classic",
    "symbol": "ETC",
    "source": "Binance",
    "start": "2018-06-12",
    "end": "2026-08-10",
    "days": 2982
  },
  {
    "slug": "pepe",
    "symbol": "PEPE",
    "source": "Binance",
    "start": "2023-05-05",
    "end": "2026-08-10",
    "days": 1194
  },
  {
    "slug": "kaspa",
    "symbol": "KAS",
    "source": "CoinGecko",
    "start": "2025-08-11",
    "end": "2026-08-10",
    "days": 365
  },
  {
    "slug": "filecoin",
    "symbol": "FIL",
    "source": "Binance",
    "start": "2020-10-15",
    "end": "2026-08-10",
    "days": 2126
  },
  {
    "slug": "arbitrum",
    "symbol": "ARB",
    "source": "Binance",
    "start": "2023-03-23",
    "end": "2026-08-10",
    "days": 1237
  },
  {
    "slug": "optimism",
    "symbol": "OP",
    "source": "Binance",
    "start": "2022-06-01",
    "end": "2026-08-10",
    "days": 1532
  },
  {
    "slug": "aptos",
    "symbol": "APT",
    "source": "Binance",
    "start": "2022-10-19",
    "end": "2026-08-10",
    "days": 1392
  },
  {
    "slug": "injective",
    "symbol": "INJ",
    "source": "Binance",
    "start": "2020-10-21",
    "end": "2026-08-10",
    "days": 2120
  },
  {
    "slug": "celestia",
    "symbol": "TIA",
    "source": "Binance",
    "start": "2023-10-31",
    "end": "2026-08-10",
    "days": 1015
  },
  {
    "slug": "sei",
    "symbol": "SEI",
    "source": "Binance",
    "start": "2023-08-15",
    "end": "2026-08-10",
    "days": 1092
  },
  {
    "slug": "render",
    "symbol": "RENDER",
    "source": "Binance",
    "start": "2024-07-26",
    "end": "2026-08-10",
    "days": 746
  },
  {
    "slug": "artificial-superintelligence-alliance",
    "symbol": "FET",
    "source": "Binance",
    "start": "2019-02-28",
    "end": "2026-08-10",
    "days": 2721
  },
  {
    "slug": "ondo",
    "symbol": "ONDO",
    "source": "Binance",
    "start": "2025-04-11",
    "end": "2026-08-10",
    "days": 487
  },
  {
    "slug": "worldcoin",
    "symbol": "WLD",
    "source": "Binance",
    "start": "2023-07-24",
    "end": "2026-08-10",
    "days": 1114
  },
  {
    "slug": "mantle",
    "symbol": "MNT",
    "source": "CoinGecko",
    "start": "2025-08-11",
    "end": "2026-08-10",
    "days": 365
  },
  {
    "slug": "sky",
    "symbol": "SKY",
    "source": "Binance",
    "start": "2025-09-17",
    "end": "2026-08-10",
    "days": 328
  },
  {
    "slug": "jupiter",
    "symbol": "JUP",
    "source": "Binance",
    "start": "2024-01-31",
    "end": "2026-08-10",
    "days": 923
  },
  {
    "slug": "lido",
    "symbol": "LDO",
    "source": "Binance",
    "start": "2022-05-09",
    "end": "2026-08-10",
    "days": 1555
  },
  {
    "slug": "curve",
    "symbol": "CRV",
    "source": "Binance",
    "start": "2020-08-15",
    "end": "2026-08-10",
    "days": 2187
  },
  {
    "slug": "pyth",
    "symbol": "PYTH",
    "source": "Binance",
    "start": "2024-02-02",
    "end": "2026-08-10",
    "days": 921
  },
  {
    "slug": "stacks",
    "symbol": "STX",
    "source": "Binance",
    "start": "2019-10-25",
    "end": "2026-08-10",
    "days": 2482
  },
  {
    "slug": "immutable",
    "symbol": "IMX",
    "source": "Binance",
    "start": "2022-01-10",
    "end": "2026-08-10",
    "days": 1674
  },
  {
    "slug": "the-graph",
    "symbol": "GRT",
    "source": "Binance",
    "start": "2020-12-17",
    "end": "2026-08-10",
    "days": 2063
  },
  {
    "slug": "thorchain",
    "symbol": "RUNE",
    "source": "Binance",
    "start": "2020-09-04",
    "end": "2026-08-10",
    "days": 2167
  },
  {
    "slug": "vechain",
    "symbol": "VET",
    "source": "Binance",
    "start": "2018-07-25",
    "end": "2026-08-10",
    "days": 2939
  },
  {
    "slug": "chiliz",
    "symbol": "CHZ",
    "source": "Binance",
    "start": "2019-09-06",
    "end": "2026-08-10",
    "days": 2531
  },
  {
    "slug": "axie-infinity",
    "symbol": "AXS",
    "source": "Binance",
    "start": "2020-11-04",
    "end": "2026-08-10",
    "days": 2106
  },
  {
    "slug": "the-sandbox",
    "symbol": "SAND",
    "source": "Binance",
    "start": "2020-08-14",
    "end": "2026-08-10",
    "days": 2188
  },
  {
    "slug": "decentraland",
    "symbol": "MANA",
    "source": "Binance",
    "start": "2020-08-06",
    "end": "2026-08-10",
    "days": 2196
  },
  {
    "slug": "bonk",
    "symbol": "BONK",
    "source": "Binance",
    "start": "2023-12-15",
    "end": "2026-08-10",
    "days": 970
  },
  {
    "slug": "dogwifhat",
    "symbol": "WIF",
    "source": "Binance",
    "start": "2024-03-05",
    "end": "2026-08-10",
    "days": 889
  },
  {
    "slug": "bittorrent",
    "symbol": "BTTC",
    "source": "Binance",
    "start": "2022-01-25",
    "end": "2026-08-10",
    "days": 1659
  }
];

const byslug = new Map(historyIndex.map((h) => [h.slug, h]));

export function getHistoryMeta(slug: string): HistoryMeta | undefined {
  return byslug.get(slug);
}

/** The newest day any series reaches — what the site can honestly claim. */
export const historyThrough: string = "2026-08-10";
