/**
 * ============================================================================
 * Investment backtest — replaying a strategy against real daily prices.
 * ============================================================================
 * The data is a static file per coin (`/data/history/<slug>.json`) generated by
 * scripts/generate-history.mjs. Serving our own snapshot rather than calling an
 * exchange from the browser buys three things: no third-party rate limit on a
 * page that could go viral, no request to an exchange revealing which coin a
 * visitor is researching, and a page that still works when the API is down.
 *
 * The cost is that the data is a snapshot. Every figure is therefore labelled
 * with the date the history actually ends — the same discipline the coin pages
 * use for `supplyAsOf`. A backtest that quietly implies it runs to today is the
 * exact failure this file is written to avoid.
 */

/** One coin's daily close series, forward-filled so index == days since start. */
export interface PriceHistory {
  slug: string;
  symbol: string;
  /** Which exchange the series came from — shown to the reader. */
  source: string;
  /** ISO date of `prices[0]`. */
  start: string;
  /** ISO date of the last entry. */
  end: string;
  prices: number[];
}

export type Strategy = "lump" | "dca";

export type Frequency = "weekly" | "biweekly" | "monthly";

export interface BacktestInput {
  strategy: Strategy;
  /** Lump sum: the whole amount. DCA: the amount per contribution. */
  amount: number;
  /** ISO date the strategy starts. Clamped to the history's own range. */
  from: string;
  /** ISO date it ends — normally the last day of history. */
  to: string;
  frequency: Frequency;
}

/** One contribution, kept so the chart and the table can show the schedule. */
export interface Contribution {
  date: string;
  /** Fiat put in on this date. */
  invested: number;
  price: number;
  /** Coin bought with it. */
  units: number;
}

/** A point on the value-over-time chart. */
export interface ValuePoint {
  /** Days since the start of the backtest. */
  day: number;
  date: string;
  /** Total fiat contributed up to this day. */
  invested: number;
  /** Market value of the accumulated units on this day. */
  value: number;
}

export interface BacktestResult {
  input: BacktestInput;
  history: Pick<PriceHistory, "symbol" | "source" | "start" | "end">;
  /** The dates actually used, after clamping to available history. */
  actualFrom: string;
  actualTo: string;
  /** True when `from` was earlier than the history and had to be moved. */
  clampedStart: boolean;

  totalInvested: number;
  units: number;
  finalValue: number;
  profit: number;
  /** Simple return on the money put in, as a percentage. */
  roi: number;
  /**
   * Compound annual growth rate, as a percentage.
   *
   * Only meaningful for a lump sum, where every unit of money was exposed for
   * the whole period. For DCA the later contributions were invested for far
   * less time, so a CAGR computed the same way flatters the result — that case
   * reports `null` and the UI shows a money-weighted return instead.
   */
  cagr: number | null;
  /** Money-weighted (IRR-style) annualised return, valid for both strategies. */
  annualised: number | null;

  firstPrice: number;
  lastPrice: number;
  /** Cheapest and dearest average entry the schedule could have achieved. */
  averageEntry: number;

  bestDay: { date: string; value: number };
  worstDrawdown: { from: string; to: string; pct: number };

  contributions: Contribution[];
  series: ValuePoint[];
}
