/**
 * Генерирует строки `/go/<slug>  <referral-url>  302` в out/_redirects из
 * src/lib/platforms.ts. Правда о реф-ссылках живёт в одном месте (platforms.ts);
 * на сайте ссылки ведут на /go/<slug> (тот же домен), Cloudflare Pages отдаёт
 * 302 на партнёрку, а клики считаются по пути /go/* в edge-аналитике —
 * без отдельного Worker и без рантайма.
 *
 * Запускается в конце `npm run build`: out/ уже собран и public/_redirects в него
 * скопирован, поэтому дописываем блок в out/_redirects (public/_redirects —
 * рукописный источник статических правил — не трогаем). Идемпотентно: свой блок
 * между маркерами каждый раз перегенерируется.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { platforms as PLATFORMS } from "../src/lib/platforms";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "out", "_redirects");
const BASE = join(ROOT, "public", "_redirects");
const START = "# --- /go/* affiliate redirects (generated by scripts/build-go-redirects.ts) ---";
const END = "# --- end /go/* ---";

function baseText(): string {
  if (existsSync(OUT)) return readFileSync(OUT, "utf8");
  if (existsSync(BASE)) return readFileSync(BASE, "utf8");
  return "";
}

function stripOld(t: string): string {
  const s = t.indexOf(START);
  if (s === -1) return t.replace(/\s+$/, "");
  const e = t.indexOf(END);
  const before = t.slice(0, s).replace(/\s+$/, "");
  const after = e === -1 ? "" : t.slice(e + END.length).replace(/^\s+/, "").replace(/\s+$/, "");
  return after ? `${before}\n\n${after}` : before;
}

const rows = PLATFORMS.filter((p) => p.url && p.slug).map(
  (p) => `/go/${p.slug}  ${p.url}  302`,
);

const block = [START, ...rows, END, ""].join("\n");
const out = `${stripOld(baseText())}\n\n${block}`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out);
console.log(`/go redirects: ${rows.length} правил → ${OUT}`);
