import type { StaticPage } from "../types";

/**
 * The page the guide byline links to.
 *
 * Written to be checkable rather than reassuring: it names the rules actually
 * followed while the tax guides were built, including the ones that cost
 * coverage (no figure without a primary source, no jurisdiction added just
 * because a competitor has it). Anything a reader could not verify — a
 * qualification, an audit, a review board — is left out, and the limits are
 * stated as plainly as the method.
 *
 * Indexed, unlike the legal pages: a policy nobody can find does no work.
 */
export const editorialPolicy: StaticPage = {
  slug: "editorial-policy",
  title: "How we verify these figures",
  description:
    "Where the numbers in our tax and staking guides come from, how they are checked, what we refuse to publish, and what this site is not qualified to tell you.",
  updatedAt: "2026-08-04",
  eyebrow: "Editorial policy",
  seo: {
    title: "Editorial Policy — How TheCryptoTools Verifies Tax Figures",
    description:
      "Our sourcing rules: primary sources only, dated checks, no invented credentials. How the crypto tax guides on TheCryptoTools are researched and corrected.",
    keywords: [
      "editorial policy",
      "how we verify crypto tax figures",
      "crypto tax sources",
      "thecryptotools methodology",
    ],
  },
  body: [
    {
      type: "p",
      text: "Crypto tax content has a specific failure mode. One site publishes a rate, a dozen others copy it, and the number keeps circulating for years after the authority changed it. Nothing in the copy tells you which one you are reading. This page exists so you can tell.",
    },

    { type: "h2", text: "Primary sources only" },
    {
      type: "p",
      text: "Every rate, threshold, allowance and deadline in our tax guides is taken from the tax authority or the legislation itself — HMRC, the IRS, the ATO, Revenue, SARS, the Bundesfinanzministerium, and their equivalents elsewhere. Accounting-firm blogs and other calculator sites are not sources, even when they agree with each other. Where a guide cites something, the link at the foot of that guide goes to the authority's own document.",
    },
    {
      type: "callout",
      text: "If we cannot find a figure in a primary source, the guide says so instead of quoting a number we cannot stand behind.",
    },

    { type: "h2", text: "Dated checks, not permanent claims" },
    {
      type: "p",
      text: "Tax rules move. Each guide carries two dates: when the page was last edited, and when its figures were last checked against the sources listed on it. The second date is the one that matters, and it only appears where the check actually happened — a guide with no verification date is telling you the truth about itself.",
    },
    {
      type: "p",
      text: "The same principle governs the coin pages: circulating supply is always printed next to the date it was read, never as a standing fact, because it changes daily.",
    },

    { type: "h2", text: "What we refuse to publish" },
    {
      type: "ul",
      items: [
        "Figures we could not confirm at the source, however widely they are repeated elsewhere.",
        "Machine-translated tax content. Rules are jurisdiction-specific, and a translated guide is a wrong guide with a confident tone.",
        "Author credentials nobody holds. This site is researched carefully; it is not written by a tax adviser, and it does not pretend otherwise.",
        "Personalised advice of any kind — nothing here knows your circumstances, and the calculators run entirely in your browser precisely because we never receive your figures.",
        "Claims about our own privacy or advertising setup that are broader than what is actually configured.",
      ],
    },

    { type: "h2", text: "Corrections" },
    {
      type: "p",
      text: "If a figure here disagrees with the authority, the authority is right and we are wrong. Send the source and we will fix the page and move its verification date. Corrections are made in place rather than quietly deleted, and a guide whose rules have changed is updated or withdrawn, not left to rot.",
    },
    {
      type: "p",
      text: "We have caught our own errors this way — an earlier draft of the country comparison table had Portugal taxing crypto-to-crypto swaps, which it does not. It was corrected before publication because the guide's own source said otherwise.",
    },

    { type: "h2", text: "The limits of this site" },
    {
      type: "p",
      text: "These guides are written to make a rule understandable and to show you the arithmetic. They cannot account for your residency history, your domicile, how you actually acquired an asset, or any of the exceptions that make real tax cases interesting. A report generated by our tax tool is a working document to hand to a professional, not a filing.",
    },
    {
      type: "p",
      text: "For anything with money on it, talk to a qualified adviser in your own jurisdiction.",
    },
  ],
};
